-- ============================================================
-- Buildway AI Core — SaaS Multi-Tenant Schema (Draft)
-- Version: 0.1.0
-- Note: This is a schema draft only. Not for production migration.
-- ============================================================

-- 1. Tenants — one row per client organisation
CREATE TABLE tenants (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name        VARCHAR(255) NOT NULL,
    industry    VARCHAR(100),                          -- e.g. construction, crm, erp
    status      VARCHAR(50)  NOT NULL DEFAULT 'active', -- active | suspended | trial
    created_at  TIMESTAMP    NOT NULL DEFAULT NOW()
);

-- 2. Users — staff/users belonging to a tenant
CREATE TABLE users (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id   UUID         NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    email       VARCHAR(255) NOT NULL,
    role        VARCHAR(50)  NOT NULL DEFAULT 'member', -- owner | admin | member | viewer
    created_at  TIMESTAMP    NOT NULL DEFAULT NOW(),
    UNIQUE (tenant_id, email)
);

-- 3. API Keys — tenant-owned external API credentials (encrypted at rest)
CREATE TABLE api_keys (
    id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id               UUID         NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    provider                VARCHAR(100) NOT NULL, -- openai | anthropic | whatsapp | etc.
    encrypted_key_placeholder TEXT        NOT NULL, -- placeholder: store encrypted value only
    status                  VARCHAR(50)  NOT NULL DEFAULT 'active', -- active | revoked
    created_at              TIMESTAMP    NOT NULL DEFAULT NOW()
);

-- 4. Knowledge Bases — RAG document collections per tenant
CREATE TABLE knowledge_bases (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id   UUID         NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    name        VARCHAR(255) NOT NULL,
    type        VARCHAR(100) NOT NULL DEFAULT 'faq', -- faq | product_catalog | sop | custom
    status      VARCHAR(50)  NOT NULL DEFAULT 'active', -- active | building | error
    created_at  TIMESTAMP    NOT NULL DEFAULT NOW()
);

-- 5. Chat Sessions — one session per customer conversation
CREATE TABLE chat_sessions (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id    UUID         NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    customer_ref VARCHAR(255),                        -- e.g. WhatsApp number, email, CRM ID
    channel      VARCHAR(100) NOT NULL DEFAULT 'web', -- whatsapp | email | web | api
    summary      TEXT,                                -- AI-generated session summary
    created_at   TIMESTAMP    NOT NULL DEFAULT NOW()
);

-- 6. Messages — individual messages within a session
CREATE TABLE messages (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    session_id  UUID         NOT NULL REFERENCES chat_sessions(id) ON DELETE CASCADE,
    role        VARCHAR(50)  NOT NULL, -- user | assistant | system
    content     TEXT         NOT NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT NOW()
);

-- 7. Actions — follow-up action items generated by AI or staff
CREATE TABLE actions (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id   UUID         NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    title       VARCHAR(500) NOT NULL,
    status      VARCHAR(50)  NOT NULL DEFAULT 'open', -- open | in_progress | done | cancelled
    priority    VARCHAR(50)  NOT NULL DEFAULT 'medium', -- low | medium | high | urgent
    created_at  TIMESTAMP    NOT NULL DEFAULT NOW()
);

-- 8. Usage Logs — token consumption and cost tracking per tenant
CREATE TABLE usage_logs (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id       UUID         NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    provider        VARCHAR(100) NOT NULL, -- openai | anthropic | etc.
    tokens_used     INTEGER      NOT NULL DEFAULT 0,
    estimated_cost  NUMERIC(10, 6) NOT NULL DEFAULT 0.000000, -- USD
    created_at      TIMESTAMP    NOT NULL DEFAULT NOW()
);

-- ============================================================
-- Indexes for common query patterns
-- ============================================================

CREATE INDEX idx_users_tenant_id          ON users(tenant_id);
CREATE INDEX idx_api_keys_tenant_id       ON api_keys(tenant_id);
CREATE INDEX idx_knowledge_bases_tenant   ON knowledge_bases(tenant_id);
CREATE INDEX idx_chat_sessions_tenant     ON chat_sessions(tenant_id);
CREATE INDEX idx_messages_session_id      ON messages(session_id);
CREATE INDEX idx_actions_tenant_id        ON actions(tenant_id);
CREATE INDEX idx_usage_logs_tenant_id     ON usage_logs(tenant_id);
CREATE INDEX idx_usage_logs_created_at    ON usage_logs(created_at);
